##########################################
# -------------- Features -------------- #
##########################################

### Various options
Damage Radius: 3.0
Only TNT: false

### Send block health if 100% health.
Always Send Health: true

### How effective explosions damage inside water/lava.
### Damage is multiplied with this if inside a liquid.
Liquid Multiplier: 0.0

### When to send block health message.
Check:
  Item: 'POTATO'
  Type: 'RIGHT_CLICK_BLOCK'

### Messages which can be translated.
### [Beta feature] Use <health> instead of <percent>
Message:
  Block health: '&9Block health: &c<percent>% hp'

### How much health the blowable blocks has.
### Use wildcard <blocks> for all blocks.
### You can also add more blocks here
Blowable Blocks Health:
  obsidian: 5.0
  enchantment_table: 5.0
  anvil: 5.0
  ender_chest: 5.0
# List of blocks here (latest): https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# List of blocks here (1.8): https://helpch.at/docs/1.8/org/bukkit/Material.html

### Health regeneration
### How many seconds until the block health is back at max health.
Regeneration Time: 3600

### Protect bedrock below chosen Y level
Bedrock Protection: 2
# Nether has an override at Y 127

### Don't touch this
Config Version: 10